### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ragmha** [ragmha/job-application#1]
- [x]  Add cover-letter
- [ ]  Add sample-template-resume
- [ ]  Add sample-template-coverLetter
- [x]  Update Resume

**Comment by ragmha** [comment]
Created a new issue for Template creation
